FROM arm32v6/alpine:3.8

ARG VERSION

RUN mkdir -p /app
WORKDIR /app

RUN cd /app \
    && wget https://github.com/prometheus/pushgateway/releases/download/v${VERSION}/pushgateway-${VERSION}.linux-armv6.tar.gz \
    && tar xzf pushgateway-${VERSION}.linux-armv6.tar.gz \
    && rm -f pushgateway-${VERSION}.linux-armv6.tar.gz \
    && mv /app/pushgateway-${VERSION}.linux-armv6/* /app/ \
    && rmdir /app/pushgateway-${VERSION}.linux-armv6

EXPOSE 9091
CMD [ "/app/pushgateway" ]

