FROM arm32v6/alpine:3.9.3

ARG VERSION

RUN mkdir /app && cd /app \
    && wget https://github.com/prometheus/pushgateway/releases/download/v${VERSION}/pushgateway-${VERSION}.linux-armv6.tar.gz \
    && tar xzf pushgateway-${VERSION}.linux-armv6.tar.gz \
    && cp pushgateway-${VERSION}.linux-armv6/pushgateway /bin/ \
    && rm -rf /app \
    && mkdir /pushgateway

COPY run.sh /run.sh
ENV PUSH_GW_VERSION=${VERSION}

EXPOSE 9091
ENTRYPOINT [ "sh", "/run.sh" ]

